/operator/direct_control/CommandCreator:
  ros__parameters:
    InvertSteeringInGearReverse:  true
    ConstraintSteeringRate:       false
    maxVelocity:                  0.05
    maxAcceleration:              4.0
    maxDeceleration:              9.0
    maxSteeringWheelAngleRate:    7.6
    minGearPosition:              1
    maxGearPosition:              3
    defaultGearPosition:          2
