<?xml version="1.0"?>
<package format="3">
    <name>tod_projection</name>
    <version>1.0.0</version>
    <description>The tod_projection package</description>
    <maintainer email="david.brecht@tum.de">David Brecht</maintainer>

    <license>LGPLv3</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>rclcpp</depend>
    <depend>nav_msgs</depend>
    <depend>tod_vehicle_msgs</depend>
    <depend>tod_helper</depend>
    <depend>tod_core</depend>
    
    <export>
      <build_type>ament_cmake</build_type>
    </export>
</package>
