Transform1:
  from: base_footprint
  to: main_lidar
  translation_x_y_z: [0.22, 0.0, 1.3]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]

Transform2:
  from: base_footprint
  to: frontcenter
  translation_x_y_z: [0.22, 0.0, 1.1]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]
