std_msgs/Header header
float32 steering_wheel_angle   # steering wheel angle position in rad
float32 steering_tire_angle    # steering tire (front wheel) angle position in rad
float32 velocity               # velocity control mode: desired speed; acceleration control mode: maximum speed
float32 acceleration           # velocity control mode: unused; acceleration control mode: desired acceleration
