Transform0:
  from: "base_link"
  to: "base_footprint"
  translation_x_y_z: [0.16, 0.0, 0.0]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]

Transform1:
  from: "base_footprint"
  to: "livox_lidar"
  translation_x_y_z: [0.16, 0.0, 0.15]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]

Transform2:
  from: "base_footprint"
  to: "bev"
  translation_x_y_z: [0.0, 0.0, 0.35]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]

Transform3:
  from: "base_footprint"
  to: "frontcenter"
  translation_x_y_z: [0.19, 0.0, 0.15]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]

Transform4:
  from: "base_footprint"
  to: "rearcenter"
  translation_x_y_z: [-0.05, 0.0, 0.15]
  rotation_yaw_pitch_roll: [0.0, 0.0, 0.0]