<?xml version="1.0"?>
<package format="3">
    <name>tod_command_forwarder</name>
    <version>1.0.0</version>
    <description>The tod_command_forwarder package</description>

    <maintainer email="david.brecht@tum.de">David Brecht</maintainer>

    <license>LGPLv3</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>tod_status_msgs</depend>
    <depend>tod_vehicle_msgs</depend>
    <depend>rclcpp</depend>
    
    <export>
        <build_type>ament_cmake</build_type>
    </export>

</package>
