/**:
  vehicle_rtsp_server:
    ros__parameters:
      rtsp_port: 8554
      image_output_format: "rgb8"
      inactivity_timeout: 3.0
  operator_rtsp_clients:
    ros__parameters:
      rtsp_port: 8554
      image_output_format: "rgb8"