<?xml version="1.0"?>
<package format="2">
    <name>tod_network_protocols</name>
    <version>1.0.0</version>
    <description>the tod_network_protocols library</description>
    <maintainer email="florian.pfab@tum.de">Florian Pfab</maintainer>
    <license>LGPLv3</license>
    <buildtool_depend>ament_cmake</buildtool_depend>
    <depend>rclcpp</depend>
    <depend>tod_status_msgs</depend>
    <depend>tod_network_msgs</depend>
  
    <test_depend>ament_cmake_gtest</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
